FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# add-edit-job

Which used to create or update the job - full job object.

## Jobs Collection [/jobs]

### List All Jobs [GET]

+ Response 200 (application/json)

        {
          "jobs": [
            {
              "jobInformation": {
                "company": "The Best",
                "title": "Best of the best",
                "description": "Some text",
                "country": "Israel",
                "city": "Yavne",
                "worksScope": "some scope",
                "maxSalary": 5000,
                "availability": "yes",
                "days": 7,
                "businessModel": "Some Model",
                "relocation": true,
                "ID": 150
              },
              "academic": [
                {"placeholder": "Text text", "value": "Professor"},
                {"placeholder": "Text text", "value": "Nobody"},
                {"placeholder": "Text text", "value": ""},
                {"placeholder": "Text text", "value": ""}
              ],
              "coursesDiplomas": [
                {"placeholder": "Text text", "value": "Diploma of nothing"},
                {"placeholder": "Text text", "value": "Diploma of everything"},
                {"placeholder": "Text text", "value": ""},
                {"placeholder": "Text text", "value": ""}
              ],
              "skillsNeeded": [
                {"selected": "JS", "knowledge": "5"},
                {"selected": "PHP", "knowledge": "8"},
                {"selected": "", "knowledge": "1"},
                {"selected": "", "knowledge": "1"}
              ],
              "languagesNeeded": [
                {"selected": "English", "knowledge": "8"},
                {"selected": "French", "knowledge": "10"},
                {"selected": "", "knowledge": "1"},
                {"selected": "", "knowledge": "1"}
              ],
              "notes": "Some interesting comment",
              "editMode": false,
              "active": true,
              "jobsCallsList": [
                {
                  "date": "2008 3 4",
                  "freeText": "Bla bla bla bla"
                },
                {
                  "date": "2009 4 5",
                  "freeText": "Olo lo lo lo lo"
                },
                {
                  "date": "2010 5 6",
                  "freeText": "Tra ta ta ta ta ta"
                }
              ]
            },
            {
              "jobInformation": {
                "company": "The Worst",
                "title": "Worst of the worst",
                "description": "Some text",
                "country": "Israel",
                "city": "Yavne",
                "worksScope": "some scope",
                "maxSalary": 5000,
                "availability": "yes",
                "days": 7,
                "businessModel": "Some Model",
                "relocation": true,
                "ID": 151
              },
              "academic": [
                {"placeholder": "Text text", "value": "Professor"},
                {"placeholder": "Text text", "value": "Nobody"},
                {"placeholder": "Text text", "value": ""},
                {"placeholder": "Text text", "value": ""}
              ],
              "coursesDiplomas": [
                {"placeholder": "Text text", "value": "Diploma of nothing"},
                {"placeholder": "Text text", "value": "Diploma of everything"},
                {"placeholder": "Text text", "value": ""},
                {"placeholder": "Text text", "value": ""}
              ],
              "skillsNeeded": [
                {"selected": "JS", "knowledge": "5"},
                {"selected": "PHP", "knowledge": "8"},
                {"selected": "", "knowledge": "1"},
                {"selected": "", "knowledge": "1"}
              ],
              "languagesNeeded": [
                {"selected": "English", "knowledge": "8"},
                {"selected": "French", "knowledge": "10"},
                {"selected": "", "knowledge": "1"},
                {"selected": "", "knowledge": "1"}
              ],
              "notes": "Some interesting comment",
              "editMode": false,
              "active": true,
              "jobsCallsList": [
                {
                  "date": "2008 3 4",
                  "freeText": "Bla bla bla bla"
                },
                {
                  "date": "2009 4 5",
                  "freeText": "Olo lo lo lo lo"
                },
                {
                  "date": "2010 5 6",
                  "freeText": "Tra ta ta ta ta ta"
                }
              ]
            },
            {
              "jobInformation": {
                "company": "Nothing special",
                "title": "Nothing of the nothing",
                "description": "Some text",
                "country": "Israel",
                "city": "Yavne",
                "worksScope": "some scope",
                "maxSalary": 5000,
                "availability": "yes",
                "days": 7,
                "businessModel": "Some Model",
                "relocation": true,
                "ID": 152
              },
              "academic": [
                {"placeholder": "Text text", "value": "Professor"},
                {"placeholder": "Text text", "value": "Nobody"},
                {"placeholder": "Text text", "value": ""},
                {"placeholder": "Text text", "value": ""}
              ],
              "coursesDiplomas": [
                {"placeholder": "Text text", "value": "Diploma of nothing"},
                {"placeholder": "Text text", "value": "Diploma of everything"},
                {"placeholder": "Text text", "value": ""},
                {"placeholder": "Text text", "value": ""}
              ],
              "skillsNeeded": [
                {"selected": "JS", "knowledge": "5"},
                {"selected": "PHP", "knowledge": "8"},
                {"selected": "", "knowledge": "1"},
                {"selected": "", "knowledge": "1"}
              ],
              "languagesNeeded": [
                {"selected": "English", "knowledge": "8"},
                {"selected": "French", "knowledge": "10"},
                {"selected": "", "knowledge": "1"},
                {"selected": "", "knowledge": "1"}
              ],
              "notes": "Some interesting comment",
              "editMode": false,
              "active": true,
              "jobsCallsList": [
                {
                  "date": "2008 3 4",
                  "freeText": "Bla bla bla bla"
                },
                {
                  "date": "2009 4 5",
                  "freeText": "Olo lo lo lo lo"
                },
                {
                  "date": "2010 5 6",
                  "freeText": "Tra ta ta ta ta ta"
                }
              ]
            },
            {
              "jobInformation": {
                "company": "Unusual company",
                "title": "Unusual of the unusual",
                "description": "Some text",
                "country": "Israel",
                "city": "Yavne",
                "worksScope": "some scope",
                "maxSalary": 5000,
                "availability": "yes",
                "days": 7,
                "businessModel": "Some Model",
                "relocation": true,
                "ID": 153
              },
              "academic": [
                {"placeholder": "Text text", "value": "Professor"},
                {"placeholder": "Text text", "value": "Nobody"},
                {"placeholder": "Text text", "value": ""},
                {"placeholder": "Text text", "value": ""}
              ],
              "coursesDiplomas": [
                {"placeholder": "Text text", "value": "Diploma of nothing"},
                {"placeholder": "Text text", "value": "Diploma of everything"},
                {"placeholder": "Text text", "value": ""},
                {"placeholder": "Text text", "value": ""}
              ],
              "skillsNeeded": [
                {"selected": "JS", "knowledge": "5"},
                {"selected": "PHP", "knowledge": "8"},
                {"selected": "", "knowledge": "1"},
                {"selected": "", "knowledge": "1"}
              ],
              "languagesNeeded": [
                {"selected": "English", "knowledge": "8"},
                {"selected": "French", "knowledge": "10"},
                {"selected": "", "knowledge": "1"},
                {"selected": "", "knowledge": "1"}
              ],
              "notes": "Some interesting comment",
              "editMode": false,
              "active": true,
              "jobsCallsList": [
                {
                  "date": "2008 3 4",
                  "freeText": "Bla bla bla bla"
                },
                {
                  "date": "2009 4 5",
                  "freeText": "Olo lo lo lo lo"
                },
                {
                  "date": "2010 5 6",
                  "freeText": "Tra ta ta ta ta ta"
                }
              ]
            },
            {
              "jobInformation": {
                "company": "Incredible company",
                "title": "Incredible of the incredible",
                "description": "Some text",
                "country": "Israel",
                "city": "Yavne",
                "worksScope": "some scope",
                "maxSalary": 5000,
                "availability": "yes",
                "days": 7,
                "businessModel": "Some Model",
                "relocation": true,
                "ID": 154
              },
              "academic": [
                {"placeholder": "Text text", "value": "Professor"},
                {"placeholder": "Text text", "value": "Nobody"},
                {"placeholder": "Text text", "value": ""},
                {"placeholder": "Text text", "value": ""}
              ],
              "coursesDiplomas": [
                {"placeholder": "Text text", "value": "Diploma of nothing"},
                {"placeholder": "Text text", "value": "Diploma of everything"},
                {"placeholder": "Text text", "value": ""},
                {"placeholder": "Text text", "value": ""}
              ],
              "skillsNeeded": [
                {"selected": "JS", "knowledge": "5"},
                {"selected": "PHP", "knowledge": "8"},
                {"selected": "", "knowledge": "1"},
                {"selected": "", "knowledge": "1"}
              ],
              "languagesNeeded": [
                {"selected": "English", "knowledge": "8"},
                {"selected": "French", "knowledge": "10"},
                {"selected": "", "knowledge": "1"},
                {"selected": "", "knowledge": "1"}
              ],
              "notes": "Some interesting comment",
              "editMode": false,
              "active": true,
              "jobsCallsList": [
                {
                  "date": "2008 3 4",
                  "freeText": "Bla bla bla bla"
                },
                {
                  "date": "2009 4 5",
                  "freeText": "Olo lo lo lo lo"
                },
                {
                  "date": "2010 5 6",
                  "freeText": "Tra ta ta ta ta ta"
                }
              ]
            },
            {
              "jobInformation": {
                "company": "Stupid",
                "title": "Stupid of the stupid",
                "description": "Some text",
                "country": "Israel",
                "city": "Yavne",
                "worksScope": "some scope",
                "maxSalary": 5000,
                "availability": "yes",
                "days": 7,
                "businessModel": "Some Model",
                "relocation": true,
                "ID": 155
              },
              "academic": [
                {"placeholder": "Text text", "value": "Professor"},
                {"placeholder": "Text text", "value": "Nobody"},
                {"placeholder": "Text text", "value": ""},
                {"placeholder": "Text text", "value": ""}
              ],
              "coursesDiplomas": [
                {"placeholder": "Text text", "value": "Diploma of nothing"},
                {"placeholder": "Text text", "value": "Diploma of everything"},
                {"placeholder": "Text text", "value": ""},
                {"placeholder": "Text text", "value": ""}
              ],
              "skillsNeeded": [
                {"selected": "JS", "knowledge": "5"},
                {"selected": "PHP", "knowledge": "8"},
                {"selected": "", "knowledge": "1"},
                {"selected": "", "knowledge": "1"}
              ],
              "languagesNeeded": [
                {"selected": "English", "knowledge": "8"},
                {"selected": "French", "knowledge": "10"},
                {"selected": "", "knowledge": "1"},
                {"selected": "", "knowledge": "1"}
              ],
              "notes": "Some interesting comment",
              "editMode": false,
              "active": true,
              "jobsCallsList": [
                {
                  "date": "2008 3 4",
                  "freeText": "Bla bla bla bla"
                },
                {
                  "date": "2009 4 5",
                  "freeText": "Olo lo lo lo lo"
                },
                {
                  "date": "2010 5 6",
                  "freeText": "Tra ta ta ta ta ta"
                }
              ]
            },
            {
              "jobInformation": {
                "company": "Rich one",
                "title": "Rich of the rich",
                "description": "Some text",
                "country": "Israel",
                "city": "Yavne",
                "worksScope": "some scope",
                "maxSalary": 5000,
                "availability": "yes",
                "days": 7,
                "businessModel": "Some Model",
                "relocation": true,
                "ID": 156
              },
              "academic": [
                {"placeholder": "Text text", "value": "Professor"},
                {"placeholder": "Text text", "value": "Nobody"},
                {"placeholder": "Text text", "value": ""},
                {"placeholder": "Text text", "value": ""}
              ],
              "coursesDiplomas": [
                {"placeholder": "Text text", "value": "Diploma of nothing"},
                {"placeholder": "Text text", "value": "Diploma of everything"},
                {"placeholder": "Text text", "value": ""},
                {"placeholder": "Text text", "value": ""}
              ],
              "skillsNeeded": [
                {"selected": "JS", "knowledge": "5"},
                {"selected": "PHP", "knowledge": "8"},
                {"selected": "", "knowledge": "1"},
                {"selected": "", "knowledge": "1"}
              ],
              "languagesNeeded": [
                {"selected": "English", "knowledge": "8"},
                {"selected": "French", "knowledge": "10"},
                {"selected": "", "knowledge": "1"},
                {"selected": "", "knowledge": "1"}
              ],
              "notes": "Some interesting comment",
              "editMode": false,
              "active": true,
              "jobsCallsList": [
                {
                  "date": "2008 3 4",
                  "freeText": "Bla bla bla bla"
                },
                {
                  "date": "2009 4 5",
                  "freeText": "Olo lo lo lo lo"
                },
                {
                  "date": "2010 5 6",
                  "freeText": "Tra ta ta ta ta ta"
                }
              ]
            },
            {
              "jobInformation": {
                "company": "Poor one",
                "title": "Poor of the poor",
                "description": "Some text",
                "country": "Israel",
                "city": "Yavne",
                "worksScope": "some scope",
                "maxSalary": 5000,
                "availability": "yes",
                "days": 7,
                "businessModel": "Some Model",
                "relocation": true,
                "ID": 157
              },
              "academic": [
                {"placeholder": "Text text", "value": "Professor"},
                {"placeholder": "Text text", "value": "Nobody"},
                {"placeholder": "Text text", "value": ""},
                {"placeholder": "Text text", "value": ""}
              ],
              "coursesDiplomas": [
                {"placeholder": "Text text", "value": "Diploma of nothing"},
                {"placeholder": "Text text", "value": "Diploma of everything"},
                {"placeholder": "Text text", "value": ""},
                {"placeholder": "Text text", "value": ""}
              ],
              "skillsNeeded": [
                {"selected": "JS", "knowledge": "5"},
                {"selected": "PHP", "knowledge": "8"},
                {"selected": "", "knowledge": "1"},
                {"selected": "", "knowledge": "1"}
              ],
              "languagesNeeded": [
                {"selected": "English", "knowledge": "8"},
                {"selected": "French", "knowledge": "10"},
                {"selected": "", "knowledge": "1"},
                {"selected": "", "knowledge": "1"}
              ],
              "notes": "Some interesting comment",
              "editMode": false,
              "active": true,
              "jobsCallsList": [
                {
                  "date": "2008 3 4",
                  "freeText": "Bla bla bla bla"
                },
                {
                  "date": "2009 4 5",
                  "freeText": "Olo lo lo lo lo"
                },
                {
                  "date": "2010 5 6",
                  "freeText": "Tra ta ta ta ta ta"
                }
              ]
            },
            {
              "jobInformation": {
                "company": "Tramp man",
                "title": "Tramps united",
                "description": "Some text",
                "country": "Israel",
                "city": "Yavne",
                "worksScope": "some scope",
                "maxSalary": 5000,
                "availability": "yes",
                "days": 7,
                "businessModel": "Some Model",
                "relocation": true,
                "ID": 158
              },
              "academic": [
                {"placeholder": "Text text", "value": "Professor"},
                {"placeholder": "Text text", "value": "Nobody"},
                {"placeholder": "Text text", "value": ""},
                {"placeholder": "Text text", "value": ""}
              ],
              "coursesDiplomas": [
                {"placeholder": "Text text", "value": "Diploma of nothing"},
                {"placeholder": "Text text", "value": "Diploma of everything"},
                {"placeholder": "Text text", "value": ""},
                {"placeholder": "Text text", "value": ""}
              ],
              "skillsNeeded": [
                {"selected": "JS", "knowledge": "5"},
                {"selected": "PHP", "knowledge": "8"},
                {"selected": "", "knowledge": "1"},
                {"selected": "", "knowledge": "1"}
              ],
              "languagesNeeded": [
                {"selected": "English", "knowledge": "8"},
                {"selected": "French", "knowledge": "10"},
                {"selected": "", "knowledge": "1"},
                {"selected": "", "knowledge": "1"}
              ],
              "notes": "Some interesting comment",
              "editMode": false,
              "active": true,
              "jobsCallsList": [
                {
                  "date": "2008 3 4",
                  "freeText": "Bla bla bla bla"
                },
                {
                  "date": "2009 4 5",
                  "freeText": "Olo lo lo lo lo"
                },
                {
                  "date": "2010 5 6",
                  "freeText": "Tra ta ta ta ta ta"
                }
              ]
            },
            {
              "jobInformation": {
                "company": "Obama man",
                "title": "Obama is the president",
                "description": "Some text",
                "country": "Israel",
                "city": "Yavne",
                "worksScope": "some scope",
                "maxSalary": 5000,
                "availability": "yes",
                "days": 7,
                "businessModel": "Some Model",
                "relocation": true,
                "ID": 159
              },
              "academic": [
                {"placeholder": "Text text", "value": "Professor"},
                {"placeholder": "Text text", "value": "Nobody"},
                {"placeholder": "Text text", "value": ""},
                {"placeholder": "Text text", "value": ""}
              ],
              "coursesDiplomas": [
                {"placeholder": "Text text", "value": "Diploma of nothing"},
                {"placeholder": "Text text", "value": "Diploma of everything"},
                {"placeholder": "Text text", "value": ""},
                {"placeholder": "Text text", "value": ""}
              ],
              "skillsNeeded": [
                {"selected": "JS", "knowledge": "5"},
                {"selected": "PHP", "knowledge": "8"},
                {"selected": "", "knowledge": "1"},
                {"selected": "", "knowledge": "1"}
              ],
              "languagesNeeded": [
                {"selected": "English", "knowledge": "8"},
                {"selected": "French", "knowledge": "10"},
                {"selected": "", "knowledge": "1"},
                {"selected": "", "knowledge": "1"}
              ],
              "notes": "Some interesting comment",
              "editMode": false,
              "active": true,
              "jobsCallsList": [
                {
                  "date": "2008 3 4",
                  "freeText": "Bla bla bla bla"
                },
                {
                  "date": "2009 4 5",
                  "freeText": "Olo lo lo lo lo"
                },
                {
                  "date": "2010 5 6",
                  "freeText": "Tra ta ta ta ta ta"
                }
              ]
            },
            {
              "jobInformation": {
                "company": "Radiation protection",
                "title": "We will protect you tomorrow",
                "description": "Some text",
                "country": "Israel",
                "city": "Yavne",
                "worksScope": "some scope",
                "maxSalary": 5000,
                "availability": "yes",
                "days": 7,
                "businessModel": "Some Model",
                "relocation": true,
                "ID": 160
              },
              "academic": [
                {"placeholder": "Text text", "value": "Professor"},
                {"placeholder": "Text text", "value": "Nobody"},
                {"placeholder": "Text text", "value": ""},
                {"placeholder": "Text text", "value": ""}
              ],
              "coursesDiplomas": [
                {"placeholder": "Text text", "value": "Diploma of nothing"},
                {"placeholder": "Text text", "value": "Diploma of everything"},
                {"placeholder": "Text text", "value": ""},
                {"placeholder": "Text text", "value": ""}
              ],
              "skillsNeeded": [
                {"selected": "JS", "knowledge": "5"},
                {"selected": "PHP", "knowledge": "8"},
                {"selected": "", "knowledge": "1"},
                {"selected": "", "knowledge": "1"}
              ],
              "languagesNeeded": [
                {"selected": "English", "knowledge": "8"},
                {"selected": "French", "knowledge": "10"},
                {"selected": "", "knowledge": "1"},
                {"selected": "", "knowledge": "1"}
              ],
              "notes": "Some interesting comment",
              "editMode": false,
              "active": true,
              "jobsCallsList": [
                {
                  "date": "2008 3 4",
                  "freeText": "Bla bla bla bla"
                },
                {
                  "date": "2009 4 5",
                  "freeText": "Olo lo lo lo lo"
                },
                {
                  "date": "2010 5 6",
                  "freeText": "Tra ta ta ta ta ta"
                }
              ]
            },
            {
              "jobInformation": {
                "company": "Red book",
                "title": "Protect the beast",
                "description": "Some text",
                "country": "Israel",
                "city": "Yavne",
                "worksScope": "some scope",
                "maxSalary": 5000,
                "availability": "yes",
                "days": 7,
                "businessModel": "Some Model",
                "relocation": true,
                "ID": 161
              },
              "academic": [
                {"placeholder": "Text text", "value": "Professor"},
                {"placeholder": "Text text", "value": "Nobody"},
                {"placeholder": "Text text", "value": ""},
                {"placeholder": "Text text", "value": ""}
              ],
              "coursesDiplomas": [
                {"placeholder": "Text text", "value": "Diploma of nothing"},
                {"placeholder": "Text text", "value": "Diploma of everything"},
                {"placeholder": "Text text", "value": ""},
                {"placeholder": "Text text", "value": ""}
              ],
              "skillsNeeded": [
                {"selected": "JS", "knowledge": "5"},
                {"selected": "PHP", "knowledge": "8"},
                {"selected": "", "knowledge": "1"},
                {"selected": "", "knowledge": "1"}
              ],
              "languagesNeeded": [
                {"selected": "English", "knowledge": "8"},
                {"selected": "French", "knowledge": "10"},
                {"selected": "", "knowledge": "1"},
                {"selected": "", "knowledge": "1"}
              ],
              "notes": "Some interesting comment",
              "editMode": false,
              "active": true,
              "jobsCallsList": [
                {
                  "date": "2008 3 4",
                  "freeText": "Bla bla bla bla"
                },
                {
                  "date": "2009 4 5",
                  "freeText": "Olo lo lo lo lo"
                },
                {
                  "date": "2010 5 6",
                  "freeText": "Tra ta ta ta ta ta"
                }
              ]
            },
            {
              "jobInformation": {
                "company": "The Last",
                "title": "Last chance",
                "description": "Some text",
                "country": "Israel",
                "city": "Yavne",
                "worksScope": "some scope",
                "maxSalary": 5000,
                "availability": "yes",
                "days": 7,
                "businessModel": "Some Model",
                "relocation": true,
                "ID": 162
              },
              "academic": [
                {"placeholder": "Text text", "value": "Professor"},
                {"placeholder": "Text text", "value": "Nobody"},
                {"placeholder": "Text text", "value": ""},
                {"placeholder": "Text text", "value": ""}
              ],
              "coursesDiplomas": [
                {"placeholder": "Text text", "value": "Diploma of nothing"},
                {"placeholder": "Text text", "value": "Diploma of everything"},
                {"placeholder": "Text text", "value": ""},
                {"placeholder": "Text text", "value": ""}
              ],
              "skillsNeeded": [
                {"selected": "JS", "knowledge": "5"},
                {"selected": "PHP", "knowledge": "8"},
                {"selected": "", "knowledge": "1"},
                {"selected": "", "knowledge": "1"}
              ],
              "languagesNeeded": [
                {"selected": "English", "knowledge": "8"},
                {"selected": "French", "knowledge": "10"},
                {"selected": "", "knowledge": "1"},
                {"selected": "", "knowledge": "1"}
              ],
              "notes": "Some interesting comment",
              "editMode": false,
              "active": true,
              "jobsCallsList": [
                {
                  "date": "2008 3 4",
                  "freeText": "Bla bla bla bla"
                },
                {
                  "date": "2009 4 5",
                  "freeText": "Olo lo lo lo lo"
                },
                {
                  "date": "2010 5 6",
                  "freeText": "Tra ta ta ta ta ta"
                }
              ]
            }
        
          ]
        }